name: Test and deploy the application
on: [push, workflow_dispatch]
jobs:
  lint-and-test:
    steps:
      - name: Clone the project
        uses: actions/checkout/v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        run: npm test
  deploy:
    steps:
      - name: Deploy the project #fake for testing
      - run: echo "Deploying...!"